Fix: LoadingMessages.tsx style error
The error `src/components/akinator-marketing-consultant/dashboard/LoadingMessages.tsx(129,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `style jsx` is being used. This commit should fix the error.